# Generated by Django 2.2.1 on 2019-05-28 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('qna', '0003_auto_20190527_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_question',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='comment_question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 5, 12, 57, 397105)),
        ),
        migrations.AlterField(
            model_name='comment_question',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='qna.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 5, 12, 57, 396113)),
        ),
    ]
