# Generated by Django 2.2.1 on 2019-06-02 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20190602_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 52, 7, 374422)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 52, 7, 373926)),
        ),
    ]
