# Generated by Django 2.2.1 on 2019-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190602_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('company', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('video', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
