# Generated by Django 2.2.1 on 2019-06-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1', models.CharField(blank=True, default='', max_length=20)),
                ('test_2', models.IntegerField(blank=True, default=5)),
                ('test_3', models.IntegerField(blank=True, default=5)),
                ('test_4', models.IntegerField(blank=True, default=5)),
                ('test_5', models.IntegerField(blank=True, default=5)),
                ('result_category', models.CharField(blank=True, default='', max_length=10)),
                ('result_product', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
