# Generated by Django 2.2.1 on 2019-06-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbytest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='test_2',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='test_3',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='test_4',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='test_5',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
