# Generated by Django 2.2.1 on 2019-05-28 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20190527_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 29, 5, 12, 57, 400080)),
        ),
    ]
