# Generated by Django 2.2.1 on 2019-06-04 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0012_auto_20190604_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 4, 17, 12, 23, 534291)),
        ),
    ]
