# Generated by Django 2.2.1 on 2019-06-07 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0014_auto_20190605_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 23, 31, 20, 709376)),
        ),
    ]
