# Generated by Django 2.2.1 on 2019-06-04 06:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 6, 4, 15, 55, 25, 866729))),
                ('files', models.ImageField(blank=True, upload_to='images/')),
                ('rate_product', models.IntegerField(blank=True, default=3)),
                ('rate_delivery', models.IntegerField(blank=True, default=3)),
                ('rate_price', models.IntegerField(blank=True, default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
